export const environment = {
  production: false,
  apiBaseUrl: 'https://therapy-connect-platform.onrender.com',
  platformProviderApiBaseUrl: 'https://therapy-connect-platform.onrender.com',
  platformProviderAuthenticationEndpointPath: '/api/v1/authentication',
  platformProviderUserProfilesEndpointPath: '/api/v1/users',
  platformProviderRolesEndpointPath: '/api/v1/roles',
  platformProviderTeacherNotesEndpointPath: '/api/v1/notes/teacher',
  platformProviderTherapySessionsEndpointPath: '/api/v1/sessions',
  platformProviderLiveSessionsEndpointPath: '/api/v1/live-sessions',
  platformProviderSessionChecklistEndpointPath: '/api/v1/session-attendance',
  platformProviderEmergenciesEndpointPath: '/api/v1/alerts',
  platformProviderEventosEndpointPath: '/api/v1/session-events',
  platformProviderRecordatoriosEndpointPath: '/api/v1/reminders',
  platformProviderCoursesEndpointPath: '/api/v1/courses',
  platformProviderRegistrationsEndpointPath: '/api/v1/registrations',
  platformProviderEvaluationsEndpointPath: '/api/v1/evaluations',
  platformProviderObservationsEndpointPath: '/api/v1/session-observations',
  platformProviderDependentsEndpointPath: '/api/v1/dependents',
  platformProviderCatalogsEndpointPath: '/api/v1/catalogs',
  platformProviderProductsEndpointPath: '/api/v1/products',
  platformProviderParentNotesEndpointPath: '/api/v1/notes/parent',
  platformProviderInstitutionalTeacherNotesEndpointPath: '/api/v1/notes/teacher/institutional',
  platformProviderPersonalTeacherNotesEndpointPath: '/api/v1/notes/teacher/personal',
};
